AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  charted-backend

  Backend for Charted

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        BUCKET_NAME: !Ref ChartedPhotoBucket

Resources:
  ChartedPhotoBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - PUT
            AllowedHeaders:
              - "*"
  UploadPhotoUrl:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: upload_photo_url/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - arm64
      Policies:
        - S3WritePolicy:
            BucketName: !Ref ChartedPhotoBucket
      Events:
        GenerateUploadPhotoUrl:
          Type: HttpApi
          Properties:
            Path: /uploadphotourl
            Method: post
  DownloadPhotoUrl:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: download_photo_url/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - arm64
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ChartedPhotoBucket
      Events:
        GenerateDownloadPhotoUrl:
          Type: HttpApi
          Properties:
            Path: /downloadphotourl
            Method: post
  DeletePhotoUrl:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_photo_url/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - arm64
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ChartedPhotoBucket
      Events:
        GenerateDeletePhotoUrl:
          Type: HttpApi
          Properties:
            Path: /deletephotourl
            Method: post

Outputs:
  UploadPhotoUrlApi:
    Description: "API Gateway endpoint URL for Upload Photo URL function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/uploadphotourl"
  DownloadPhotoUrlApi:
    Description: "API Gateway endpoint URL for Download Photo URL function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/downloadphotourl"
  DeletePhotoUrlApi:
    Description: "API Gateway endpoint URL for Delete Photo URL function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/deletephotourl"
